DEFINE
    MEASURE 'Fact'[VersionSwitch] =
        SWITCH (
            IF (
                SELECTEDVALUE ( 'Date'[Year], 1 ) <> 0,
                1,
                 (
                    IF (
                        SELECTEDVALUE ( 'Product'[Product] ) <> "",
                        IF ( SELECTEDVALUE ( Executive[Name] ) <> "", 2, 3 ),
                        2
                    )
                )
            ),
            1, 'Fact'[# of Customers],
            2, 'Fact'[# of Products],
            3, 'Fact'[COGS SPLY],
            4, 'Fact'[GM% SPLY],
            5, 'Fact'[Gross Margin],
            6, 'Fact'[Gross Margin SPLY],
            8, 'Fact'[Revenue Var % to Budget]
        )
    MEASURE 'Fact'[VersionSwitch2] =
        VAR condition1 =
            IF (
                SELECTEDVALUE ( 'Product'[Product] ) <> "",
                IF ( SELECTEDVALUE ( Executive[Name] ) <> "", 2, 3 ),
                1
            )
        VAR condition2 =
            IF ( SELECTEDVALUE ( 'Date'[Year], 1 ) <> 0, 1, condition1 )
        RETURN
            SWITCH (
                condition2,
                1, 'Fact'[# of Customers],
                2, 'Fact'[# of Products],
                3, 'Fact'[COGS SPLY],
                4, 'Fact'[GM% SPLY],
                5, 'Fact'[Gross Margin],
                6, 'Fact'[Gross Margin SPLY],
                8, 'Fact'[Revenue Var % to Budget]
            )

 EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
    'Product'[Product],
    "test", [VersionSwitch2],
    "test2", 'Fact'[# of Customers]
)