DEFINE
    MEASURE 'Fact'[VersionSwitch3] =
        IF (
            DISTINCTCOUNT ( [Customer Key] ) > 0,
            CALCULATE (
                DISTINCTCOUNT ( [Customer Key] ),
                SAMEPERIODLASTYEAR ( 'Date'[Date] )
            ),
            CALCULATE ( DISTINCTCOUNT ( [Customer Key] ), DATESYTD ( ( 'Date'[Date] ) ) )
        )
    MEASURE 'Fact'[VersionSwitch4] =
        VAR condition1 =
            IF ( DISTINCTCOUNT ( [Customer Key] ) > 0, 1, 0 )
        VAR firstMeasure =
            CALCULATE (
                DISTINCTCOUNT ( [Customer Key] ),
                SAMEPERIODLASTYEAR ( 'Date'[Date] )
            )
        VAR secondMeasure =
            CALCULATE ( DISTINCTCOUNT ( [Customer Key] ), DATESYTD ( ( 'Date'[Date] ) ) )
        RETURN
            IF ( condition1, firstMeasure, secondMeasure )
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
     'Product'[Product],
     BU[BU],
     Customer[City],
     Customer[Name],
    Industry[Image],
     "test", [VersionSwitch3]--,
    --"test2", [VersionSwitch4]
)